apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  labels:
    app: collector
  namespace: swirlai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: collector:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: APP_ENV
            value: Dev
