apiVersion: v1
kind: Pod
metadata:
  name: producer-1
  namespace: swirlai
spec:
  containers:
  - name: producer
    image: producer:latest
    imagePullPolicy: Never
    env:
    - name: DATA_URL
      value: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet

---

apiVersion: v1
kind: Pod
metadata:
  name: producer-2
  namespace: swirlai
spec:
  containers:
  - name: producer
    image: producer:latest
    imagePullPolicy: Never
    env:
    - name: DATA_URL
      value: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet

---

apiVersion: v1
kind: Pod
metadata:
  name: producer-3
  namespace: swirlai
spec:
  containers:
  - name: producer
    image: producer:latest
    imagePullPolicy: Never
    env:
    - name: DATA_URL
      value: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-03.parquet